language: node_js
node_js:
    - '9'
script: yarn build && touch ./out/.nojekyll
evn:
    NODE_ENV: production
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
        branch: master
    local-dir: ./out
    fqdn: howtodothisinflutter.com
